id = "sculpt"
version = "0.2.3"
namespace = "com.github.glassmc.sculpt"

implementations = [
    "1.8.9"
]

[listeners]
initialize = [
    "SculptInitializeListener"
]

[environment]
    [environment.has]
    client = "1.8.9"